{
 "title": "RTSP Metrics",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "500ms",
 "panels": [
  { "title": "Media", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Frames Per Second",
   "type": "timeseries",
   "description": "Frames per second of a video stream.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "frames_per_second", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Average Frames Per Second",
   "type": "gauge",
   "description": "The average frames per second (FPS) calculated over the entire selected time range of the dashboard.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(frames_per_second[$__range])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "RTSP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Session Bytes Received",
   "type": "timeseries",
   "description": "Total bytes received during the session.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "session_bytes_received", "legendFormat": "{{name}}" }
   ]
  },
  { "title": "RTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Average RTP Jitter",
   "type": "timeseries",
   "description": "Average RTP jitter during the session.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    { "expr": "session_rtp_jitter", "legendFormat": "{{name}}" }
   ]
  },
  { "title": "Golang", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Memory Allocations",
   "type": "timeseries",
   "description": "Heap Memory Allocations: number of bytes allocated in heap and currently in use.\n\nStack Memory Allocations: number of bytes obtained from system for stack allocator in non-CGO environments.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "{{__name__}}" },
    { "expr": "go_memstats_stack_inuse_bytes", "legendFormat": "{{ __name__ }}" }
   ]
  }
 ]
}